version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ./server/data.db:/app/server/data.db
